name: Domain Expiry Check

on:
  schedule:
    - cron: "0 8 * * *"   # 每天 08:00 UTC 执行一次
  workflow_dispatch:       # 手动触发

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.0

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run check
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python check.py